<?php
 $objm = \Magento\Framework\App\ObjectManager::getInstance(); ?>
    <?php $customerSession = $objm->get('Magento\Customer\Model\Session'); ?>




<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">

    <div class="field phone required">
        <label for="phone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
        <div class="control">

            <input type="text" name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>"
                    value="<?php echo $customerSession->getCustomer()->getPhone();?>"
                   class="input-text"  autocomplete="off"
                   data-validate="{required:true, 'validate-phoneLax':true}"
            />
            </div>
    </div>


    </fieldset>